### ISSUE TITLE
Restrict install_requires to exclude pyglet 1.4+

### ISSUE THREAD

**Issue by MartinHowarth** [los-cocos/cocos#318]
cocos2d currently works on pyglet==1.3.2
It does not work on 1.4+ (specifically I've tested 1.4.1) as this is a new major release which has removed some methods.

E.g. the hello_world.py sample gives this error because `ClockDisplay` has been removed.
```
Traceback (most recent call last):
  File "C:/Users/Martin/PycharmProjects/town_td_game/town_td/hello_world.py", line 11, in <module>
    import cocos
  File "C:\Users\Martin\PycharmProjects\town_td_game\venv\lib\site-packages\cocos\__init__.py", line 107, in <module>
    from cocos import cocosnode
  File "C:\Users\Martin\PycharmProjects\town_td_game\venv\lib\site-packages\cocos\cocosnode.py", line 51, in <module>
    from cocos.director import director
  File "C:\Users\Martin\PycharmProjects\town_td_game\venv\lib\site-packages\cocos\director.py", line 134, in <module>
    import cocos.fps
  File "C:\Users\Martin\PycharmProjects\town_td_game\venv\lib\site-packages\cocos\fps.py", line 56, in <module>
    from pyglet.clock import ClockDisplay
ImportError: cannot import name 'ClockDisplay' from 'pyglet.clock' (C:\Users\Martin\PycharmProjects\town_td_game\venv\lib\site-packages\pyglet\clock.py)
```

I'm happy to work with `pyglet==1.3.2` for now so supporting the new version isn't urgent; however please can you update the setup.py install_requires to include `pyglet<1.4` (or similar) so other newcomers like me don't have to work this out! :)

**Comment by ccanepa** [comment]
done, both pypi and master, v 0.6.6

**Comment by ramAdam** [comment]
@ccanepa I am getting this error on linux machine, can you please help

`Traceback (most recent call last):
  File "/home/z3ro/.virtualenvs/coco2d/lib/python3.7/site-packages/cocos/fps.py", line 57, in <module>
    from pyglet.clock import ClockDisplay
ImportError: cannot import name 'ClockDisplay' from 'pyglet.clock' (/home/z3ro/.virtualenvs/coco2d/lib/python3.7/site-packages/pyglet/clock.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cocodemo.py", line 1, in <module>
    import cocos
  File "/home/z3ro/.virtualenvs/coco2d/lib/python3.7/site-packages/cocos/__init__.py", line 113, in <module>
    from cocos import cocosnode
  File "/home/z3ro/.virtualenvs/coco2d/lib/python3.7/site-packages/cocos/cocosnode.py", line 51, in <module>
    from cocos.director import director
  File "/home/z3ro/.virtualenvs/coco2d/lib/python3.7/site-packages/cocos/director.py", line 134, in <module>
    import cocos.fps
  File "/home/z3ro/.virtualenvs/coco2d/lib/python3.7/site-packages/cocos/fps.py", line 59, in <module>
    from pyglet.window import FPSDisplay as ClockDisplay
  File "/home/z3ro/.virtualenvs/coco2d/lib/python3.7/site-packages/pyglet/window/__init__.py", line 1890, in <module>
    gl._create_shadow_window()
  File "/home/z3ro/.virtualenvs/coco2d/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 209, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/z3ro/.virtualenvs/coco2d/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/z3ro/.virtualenvs/coco2d/lib/python3.7/site-packages/pyglet/window/__init__.py", line 642, in __init__
    self._create()
  File "/home/z3ro/.virtualenvs/coco2d/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 265, in _create
    self.context.set_vsync(self._vsync) # XXX ?
  File "/home/z3ro/.virtualenvs/coco2d/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 256, in set_vsync
    glxext_arb.glXSwapIntervalEXT(interval)
TypeError: this function takes at least 3 arguments (1 given)
(coco2d)`

**Comment by ccanepa** [comment]
Hi ramAdam, thanks for your report.

Hmmm. It is a pyglet error,
 
That error was fixed in pyglet at 2019 09 09, commit https://github.com/pyglet/pyglet/commit/2d55998bb0c69f6507928459997800444a4183b4 

 which was after 1.4.3 and before 1.4.4 ( ref:   https://github.com/pyglet/pyglet/commits/pyglet-1.4-maintenance?after=ed3f0f08fb9da680a685570ce42467ee7bdd7bb3+69 )

And I see the last released cocos , 0.6.7, was out the 6th September, and it pins the pyglet version at 1.4.3

Could you update pyglet to last version ? With  your environment activated, something similar to
```
pip install --upgrade pyglet
```
should install the latest available in pypi, currently 1.4.7

**Don't** unistall and install cocos, it would pick 1.4.3

After doing some testing with 1.4.7 I will update the required pyglet version.

**Comment by ramAdam** [comment]
@ccanepa thanks
